server:
  port: 9406
spring:
  #配置数据连接
  datasource:
    url: jdbc:mysql://localhost:3306/general
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/mapper-*.xml
  type-aliases-package: com.zacharyz.general.bean
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    #字符串全局唯一id（详见IdType.class）
    id-type: 2
    #表名和字段名是否使用下划线命名,即实体类属性与数据库表中字段驼峰与下划线自动转换，不需要完全一致
    db-column-underline: true